import {useState} from "react";
import {Shell,type NavItem} from "./Shell";
import {Icon} from "./ui";
import {CalendarToolbar,ScheduleCalendar} from "./ScheduleCalendar";
import {day} from "./data";
import type {CalendarView} from "./calendar";
const nav:NavItem[]=[{name:"대시보드",icon:"home",english:"Home"},{name:"일정",icon:"calendar",english:"Schedule"},{name:"돌봄 기록",icon:"clock",english:"Records"},{name:"가족 관리",icon:"users",english:"Family"},{name:"AI 비서",icon:"mic",english:"Assistant"}];
export function GuestApp({onStart}:{onStart:(intent:"create"|"join"|"login")=>void}){
 const [page,setPage]=useState("대시보드");const [date,setDate]=useState(day());const [view,setView]=useState<CalendarView>("month");const [period,setPeriod]=useState("오늘");
 const start=<div className="button-row"><button className="primary" onClick={()=>onStart("create")}>그룹 만들기</button><button className="secondary" onClick={()=>onStart("join")}>초대 코드로 참여</button></div>;
 const empty=(title:string,description:string)=><section className="card guest-empty"><Icon name="heart" size={32}/><h2>{title}</h2><p>{description}</p>{start}</section>;
 return <Shell guest page={page} navItems={nav} navigate={setPage} name="둘러보기" onProfileClick={()=>onStart("login")} toast="" onToastClose={()=>{}}><div className="guest-banner"><span><strong>먼저 둘러보세요</strong> · 그룹을 만들거나 참여하면 우리 가족의 기록을 시작할 수 있어요.</span><small>개인정보가 없는 둘러보기 화면</small></div><div className="page-heading"><div><p className="eyebrow">함께 돌보는, 우리 가족</p><h1>{page==="대시보드"?"가족의 돌봄을 함께 이어가요":page==="가족 관리"?"가족":page}</h1></div>{start}</div>
 {page==="대시보드"?<><section className="ux-care-hero"><div><span className="ux-pill">Family Care Cloud</span><h2>하루의 기록을 나누고,<br/>다음 돌봄을 준비하세요.</h2><p>일정과 돌봄 기록을 한곳에서 확인할 수 있어요.</p></div><Icon name="heart" size={64}/></section><div className="guest-features">{[["일정","calendar","진료와 가족 방문 일정을 함께 확인해요."],["돌봄 기록","file","식사, 복약, 일상의 변화를 남겨요."],["가족 관리","users","함께 돌볼 가족을 초대하고 교대해요."],["AI 비서","mic","돌봄 기록을 바탕으로 질문해요."]].map(([label,icon,desc])=><button className="card guest-feature" key={label} onClick={()=>setPage(label)}><Icon name={icon as NavItem['icon']} size={28}/><h2>{label==="가족 관리"?"가족":label}</h2><p>{desc}</p><span>둘러보기 →</span></button>)}</div></>:page==="일정"?<><CalendarToolbar date={date} view={view} onDate={setDate} onView={setView}/><section className="card cal-panel"><div className="cal-summary"><strong>그룹 참여 후 가족의 일정을 등록할 수 있어요.</strong></div><ScheduleCalendar date={date} view={view} schedules={[]} onSelectDate={d=>{setDate(d);setView("day")}} onSelectEvent={()=>{}}/></section></>:page==="돌봄 기록"?<><div className="records-period">{["오늘","이번 주","지난 기록"].map(x=><button key={x} aria-pressed={period===x} className={period===x?"active":""} onClick={()=>setPeriod(x)}>{x}</button>)}</div>{empty("우리 가족의 이야기를 남길 공간","그룹에 참여하면 날짜별 돌봄 기록과 브리핑을 확인할 수 있어요.")}</>:page==="가족 관리"?empty("함께 돌볼 가족을 연결해요","새 그룹을 만들거나 가족에게 받은 초대 코드로 참여하세요. 선택한 다음 로그인하면 이어서 진행돼요."):empty("돌봄에 대해 궁금한 점을 물어보세요","그룹에 참여한 뒤 텍스트나 음성으로 일정과 돌봄 기록에 대해 질문할 수 있어요.")}</Shell>;
}
