import {useEffect,useRef,useState} from "react";
import {day,localInput,timeLabel,type Schedule} from "./data";
import {Icon} from "./ui";
import {calendarDays,shiftDate,dateKey,type CalendarView} from "./calendar";
const weekdays=["일","월","화","수","목","금","토"];
function kindClass(kind:string){return kind==="복약"?"medication":kind==="병원"||kind==="검사"?"medical":"daily";}
export function ScheduleCalendar({date,view,schedules,onSelectDate,onSelectEvent}:{date:string;view:CalendarView;schedules:Schedule[];onSelectDate:(date:string)=>void;onSelectEvent:(id:string)=>void}){
 const [now,setNow]=useState(()=>new Date());const scroller=useRef<HTMLDivElement>(null);
 useEffect(()=>{const id=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(id);},[]);
 useEffect(()=>{if(scroller.current)scroller.current.scrollTop=7*64;},[view,date]);
 const days=calendarDays(date,view); const today=day();
 const forDay=(d:string)=>schedules.filter(s=>localInput(s.scheduledAt).slice(0,10)===d).sort((a,b)=>Date.parse(a.scheduledAt)-Date.parse(b.scheduledAt));
 const event=(s:Schedule)=><button key={s.scheduleId} className={`cal-event ${kindClass(s.kind)} ${s.status==="취소"?"cancelled":""}`} onClick={()=>onSelectEvent(s.scheduleId)} aria-label={`${timeLabel(s.scheduledAt)} ${s.title} · ${s.status} 상세`}><span>{timeLabel(s.scheduledAt)} · {s.status}</span><strong>{s.title}</strong></button>;
 if(view==="month") return <div className="cal-month"><div className="cal-weekdays">{weekdays.map(w=><span key={w}>{w}</span>)}</div><div className="cal-month-grid">{days.map(d=>{const entries=forDay(d);return <div key={d} className={`cal-month-cell ${d.slice(0,7)!==date.slice(0,7)?"outside":""}`}><button className={`cal-date ${d===today?"is-today":""} ${d===date?"chosen":""}`} onClick={()=>onSelectDate(d)} aria-label={`${d} 일정 보기`}>{Number(d.slice(-2))}</button><div className="cal-month-events">{entries.slice(0,2).map(event)}</div>{entries.length>0&&<button className="cal-count" onClick={()=>onSelectDate(d)} aria-label={`${d} 일정 ${entries.length}건 보기`}><span className="cal-dots">{entries.slice(0,3).map(s=><i key={s.scheduleId} className={kindClass(s.kind)}/>)}</span><span>{entries.length}건</span></button>}</div>;})}</div></div>;
 return <div className="cal-scroll" ref={scroller} tabIndex={0} aria-label={view==="week"?"주간 시간표, 가로 세로 스크롤 가능":"하루 시간표"}><div className={`cal-time-grid ${view}`}><div className="cal-time-head"><span>시간</span>{days.map((d,i)=><button key={d} onClick={()=>onSelectDate(d)} className={d===today?"is-today":""}>{view==="day"?"선택한 날짜":weekdays[i]} <b>{Number(d.slice(-2))}</b></button>)}</div>{Array.from({length:24},(_,hour)=><div className="cal-hour" key={hour}><time>{String(hour).padStart(2,"0")}:00</time>{days.map(d=><div className="cal-hour-cell" key={d}>{forDay(d).filter(s=>new Date(s.scheduledAt).getHours()===hour).map(event)}{d===today&&now.getHours()===hour&&<div className="cal-now" style={{top:`${now.getMinutes()/60*100}%`}}><span>{timeLabel(now.toISOString())}</span></div>}</div>)}</div>)}</div></div>;
}
export function CalendarToolbar({date,view,onDate,onView}:{date:string;view:CalendarView;onDate:(d:string)=>void;onView:(v:CalendarView)=>void}){
 const dates=calendarDays(date,"week");const label=view==="month"?`${date.slice(0,4)}년 ${Number(date.slice(5,7))}월`:view==="week"?`${dates[0].replaceAll("-",".")} — ${dates[6].slice(5).replace("-",".")}`:new Date(date+"T12:00").toLocaleDateString("ko-KR",{year:"numeric",month:"long",day:"numeric",weekday:"short"});
 const move=(n:number)=>{if(view!=="month")onDate(shiftDate(date,n*(view==="week"?7:1)));else{const d=new Date(date+"T12:00");d.setDate(1);d.setMonth(d.getMonth()+n);onDate(dateKey(d));}};
 return <div className="cal-toolbar"><div className="cal-view-tabs" aria-label="일정 보기">{([["day","오늘"],["week","주간"],["month","월간"]] as const).map(([key,text])=><button key={key} aria-pressed={view===key} className={view===key?"active":""} onClick={()=>{onView(key);if(key==="day")onDate(day());}}>{text}</button>)}</div><div className="cal-date-controls"><button aria-label="이전 기간" onClick={()=>move(-1)}><Icon name="chevron" size={18}/></button><h2>{label}</h2><button aria-label="다음 기간" onClick={()=>move(1)}><Icon name="chevron" size={18}/></button></div><button className="secondary cal-today" onClick={()=>onDate(day())}>오늘로</button></div>;
}
